AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SignalQueue: 
    Type: AWS::SQS::Queue
  SignalInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref LambdaSignal
      Action: 'lambda:InvokeFunction'
      Principal: 'sqs.amazonaws.com'
      SourceArn: !GetAtt SignalQueue.Arn
  SignalEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt SignalQueue.Arn
      FunctionName: !GetAtt LambdaSignal.Arn
      BatchSize: 1
  LambdaSignalRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
  LambdaSignalUserPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      Roles: 
        - '{{resolve:ssm:/heron/heron-user-rolename}}'
      PolicyName: 'lambdasignal-user-send'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Action: 
              - 'sqs:SendMessage'
            Resource: !GetAtt SignalQueue.Arn
  LambdaSignalCorePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      Roles: 
        - !Ref LambdaSignalRole
      PolicyName: 'lambdasignal-base'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Action: 
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:ChangeMessageVisibility'
            Resource: !GetAtt SignalQueue.Arn
          - Effect: 'Allow'
            Action: 
              - 's3:GetObject'
            Resource: 
              - 'arn:aws:s3:::{{resolve:ssm:/heron/config-bucket-name}}/*/uuid'
              - 'arn:aws:s3:::{{resolve:ssm:/heron/config-bucket-name}}/*/config.json'
          - Effect: 'Allow'
            Action: 
              - 'ssm:GetParameter'
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/heron/signal-lambda/*'
          - Effect: 'Allow'
            Action: 
              - 'ssm:GetParameter'
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/heron/config-bucket-name'
  LambdaSignal:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaSignalRole
    Properties:
      Role: !GetAtt LambdaSignalRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.9
      Timeout: 25
      MemorySize: 128
      Code:
        ZipFile: |
          import boto3
          import botocore
          import os
          import json

          def lambda_handler(event, context):
              print(event)
              ssm = boto3.client('ssm')
              config_bucket_param = ssm.get_parameter(
                Name = '/heron/config-bucket-name',
                WithDecryption = False
              )
              config_bucket = config_bucket_param['Parameter']['Value']

              payload = json.loads(event['Records'][0]['body'])
              date = payload['date']
              identityid = payload['identityID']
              submitteduuid = payload['uuid']
              s3 = boto3.resource('s3')
              obj = s3.Object(config_bucket, identityid + '/uuid').get()
              uuid = obj['Body'].read().decode('utf-8')
              print(uuid);
              if submitteduuid != uuid:
                print('Illegal ID ' + submitteduuid)
                return
              try:
                obj = s3.Object(config_bucket, identityid + '/config.json').get()
              except botocore.exceptions.ClientError as e:
                if e.response['Error']['Code'] == "AccessDenied":
                      print("No config file found skipping")
                      return
                else:
                    raise
              config = json.loads(obj['Body'].read().decode('utf-8'))
              for signal in config['signals']:
                signaltargetsqs_param = ssm.get_parameter(
                  Name='/heron/signal-lambda/' + signal['signal-type']
                )
                sqs = boto3.client('sqs')
                message = {
                  'config': signal['config'],
                  'date': date,
                  'identityID': identityid
                }
                sqs.send_message(
                  QueueUrl=signaltargetsqs_param['Parameter']['Value'],
                  MessageBody = json.dumps(message)
                )

  LambdaRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/heron/heron-signal-lambda-rolename'
      Type: String
      Value: !Ref LambdaSignalRole
Outputs:
  SignalQueueURL:
    Value: !Ref SignalQueue
