AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TwitterQueue: 
    Type: AWS::SQS::Queue
  TwitterInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref LambdaTwitter
      Action: 'lambda:InvokeFunction'
      Principal: 'sqs.amazonaws.com'
      SourceArn: !GetAtt TwitterQueue.Arn
  TwitterEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt TwitterQueue.Arn
      FunctionName: !GetAtt LambdaTwitter.Arn
  
  TwitterLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
  LambdaSignalLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      Roles:
        - '{{resolve:ssm:/heron/heron-signal-lambda-rolename}}'
      PolicyName: 'lambdasignal-send-twitter'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Action: 
              - 'sqs:SendMessage'
            Resource: !GetAtt TwitterQueue.Arn
          - Effect: 'Allow'
            Action: 
              - 'ssm:GetParameter'
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${TwitterSQSParameter}'
  TwitterLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: 'lambdatwitter'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Action: 
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:ChangeMessageVisibility'
            Resource: !GetAtt TwitterQueue.Arn
          - Effect: 'Allow'
            Action: 
              - 'ssm:GetParameter'
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/heron/heron-video-domain'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/heron/heron-dashboard-domain'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/heron/video-bucket-name'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/heron/config-bucket-name'
          - Effect: 'Allow'
            Action: 
              - 'secretsmanager:GetSecretValue'
            Resource:
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:heron/integrations/twitter-??????'
          - Effect: 'Allow'
            Action: 
              - 's3:PutObject'
            Resource: 'arn:aws:s3:::{{resolve:ssm:/heron/video-bucket-name}}/*/*/*'
          - Effect: 'Allow'
            Action: 
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: 'arn:aws:s3:::{{resolve:ssm:/heron/config-bucket-name}}/*/twittertoken'
      Roles: 
        - !Ref TwitterLambdaRole
  LambdaTwitter:
    Type: AWS::Lambda::Function
    DependsOn:
      - TwitterLambdaRole
    Properties:
      Role: !GetAtt TwitterLambdaRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.10
      Timeout: 25
      MemorySize: 128
      Code:
        S3Bucket: '{{resolve:ssm:/heron/deploy-resource-bucket-name}}'
        S3Key: 
          !Join
            - '/'
            - - 'lambdas'
              - 'heron-signal-twitter'
              - '{{resolve:ssm:/heron/latest/lambda-build}}'
              - 'index.zip'
      Layers:
        - '{{resolve:ssm:/heron/heron-lambda-layer-tweepy}}'


  TwitterSQSParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/heron/signal-lambda/twitter'
      Type: String
      Value: !GetAtt TwitterQueue.QueueName




